### ISSUE TITLE
Verification module is undefined if the signing secret key is not provided

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/formsg-javascript-sdk#45]
The runtime SDK has the strange behavior where the verification module is missing if the signing secret key isn’t provided.

Initially thought to be a smart way to protect the SDK user, this design actually causes the need for type coercion in the verification service within the main Forms codebase (see https://github.com/opengovsg/FormSG/issues/941).

Change the behavior of the SDK to throw an exception instead.

**Comment by frankchn** [comment]
I suspect I am probably missing something here, but seems like [the `Verification` module is always constructed upon package initialization](https://github.com/opengovsg/formsg-javascript-sdk/blob/develop/src/index.ts#L29-L33), and [the current code does throw an `Exception` when the verification module is being used without a secret key](https://github.com/opengovsg/formsg-javascript-sdk/blob/develop/src/verification/index.ts#L114-L116).

**Comment by karrui** [comment]
Yes, this should have been fixed in #38. This is just not pushed to npm yet
